import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useNavigate } from 'react-router-dom';
import { Menu } from 'lucide-react';
import LanguageSwitcher from '@/components/LanguageSwitcher';
import AvatarImage from '@/components/AvatarImage';
import { useTranslation } from 'react-i18next';
const AppHeader = ({ onMenuClick }) => {
    const navigate = useNavigate();
    const { t } = useTranslation(['header']);
    return (_jsx("header", { className: "bg-white/90 backdrop-blur-xl border-b border-pink-200/50 shadow-lg flex-shrink-0 fixed top-0 left-0 right-0 z-30", children: _jsx("div", { className: "w-full px-4 py-2", children: _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { className: "flex items-center gap-3", children: [onMenuClick && (_jsx("button", { onClick: onMenuClick, className: "p-2.5 hover:bg-pink-100 rounded-xl transition-all duration-200 hover:scale-105", "aria-label": "Toggle menu", children: _jsx(Menu, { className: "h-5 w-5 text-pink-600" }) })), _jsxs("button", { onClick: () => navigate('/'), className: "flex items-center space-x-3 hover:opacity-90 transition-opacity group", children: [_jsxs("div", { className: "relative", children: [_jsx(AvatarImage, { size: "small" }), _jsx("div", { className: "absolute -bottom-0.5 -right-0.5 w-3 h-3 bg-pink-500 rounded-full border-2 border-white" })] }), _jsxs("div", { children: [_jsx("h1", { className: "text-base font-bold bg-gradient-to-r from-pink-500 via-rose-500 to-pink-600 bg-clip-text text-transparent group-hover:from-pink-600 group-hover:via-rose-600 group-hover:to-pink-700 transition-all", children: t('header:appName') }), _jsx("div", { className: "flex items-center gap-2 text-xs", children: _jsx("span", { className: "text-pink-600", children: t('header:appSubtitle') }) })] })] })] }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsx(LanguageSwitcher, {}), _jsxs("button", { onClick: () => navigate('/feedback'), className: "relative group overflow-hidden rounded-xl px-4 py-2 font-semibold text-sm transition-all duration-300 hover:scale-105 shadow-md hover:shadow-lg", children: [_jsx("div", { className: "absolute inset-0 bg-gradient-to-r from-pink-500 via-purple-500 to-blue-500 animate-gradient-x" }), _jsx("div", { className: "absolute inset-0 opacity-0 group-hover:opacity-100 transition-opacity duration-300", children: _jsx("div", { className: "absolute inset-0 bg-gradient-to-r from-pink-400 via-purple-400 to-blue-400 blur-sm" }) }), _jsx("div", { className: "absolute inset-0", children: _jsx("div", { className: "absolute top-0 left-0 w-full h-full bg-gradient-to-r from-transparent via-white to-transparent opacity-30 animate-shimmer" }) }), _jsxs("div", { className: "relative flex items-center gap-2 text-white", children: [_jsx("span", { className: "text-base", children: "\uD83D\uDCEE" }), _jsx("span", { children: t('header:feedbackButton') })] })] })] })] }) }) }));
};
export default AppHeader;
